spring:                                # ??? ?? ??? ??
  application:
    name: sbb                         # ?????? ??(??, ????? ??? ??)

  output:
    ansi:
      enabled: always                 # ?? ANSI ?? ?? ?? ??(?? ????)

  profiles:
    active: dev                       # ?? ?? ???? 'dev'? ??

  jpa:
    show-sql: true                    # JPA? ???? SQL? ??? ??(???)
    hibernate:
      ddl-auto: update                # ??? ?? ????(???; ???? ???)
      #  - create / create-drop / update / validate / none
    properties:
      hibernate:
        format_sql: true              # SQL? ?? ?? ???/????
        highlight_sql: true           # SQL ??? ?????(ANSI ??; Hibernate 6+)
        use_sql_comments: true        # ???? SQL? ?? ??(???/?? ?? ??)

    logging:                          # ?? ??: ????? 'logging.level'? ??? ?? ???.
      level:                          #     jpa ??? ?? ???? ?? ? ???.
        org.hibernate.orm.jdbc.bind: TRACE     # ???? ???? ? ??(Hibernate 6+)
        org.hibernate.orm.jdbc.extract: TRACE  # JDBC??? ?? ? ??(Hibernate 6+)
        org.springframework.transaction.interceptor: TRACE  # ???? ??/??/?? ??